# -*- coding: utf-8 -*-
"""voucher.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v5mpPOlJJ80WQQ5iIQRkFygl7tEHwf-F
"""

# voucher_app.py
# A complete Streamlit web application for Voucher Code Discount Calculator
# Run with: streamlit run voucher_app.py

import streamlit as st
import pandas as pd
import json
import time
from datetime import datetime
import random
import re

# Page configuration
st.set_page_config(
    page_title="Voucher Discount Calculator",
    page_icon="🎫",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Custom CSS for beautiful design
st.markdown("""
<style>
    /* Main container styling */
    .main {
        padding: 0rem 1rem;
    }

    /* Header styling */
    .header-container {
        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
        padding: 2rem;
        border-radius: 20px;
        margin-bottom: 2rem;
        text-align: center;
        color: white;
    }

    /* Card styling */
    .card {
        background: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%);
        padding: 2rem;
        border-radius: 15px;
        box-shadow: 0 4px 6px rgba(0,0,0,0.1);
        margin-bottom: 1rem;
    }

    /* Voucher card */
    .voucher-card {
        background: linear-gradient(135deg, #fa709a 0%, #fee140 100%);
        padding: 1.5rem;
        border-radius: 15px;
        text-align: center;
        margin: 1rem 0;
    }

    /* Price display */
    .price-box {
        background: linear-gradient(135deg, #a8edea 0%, #fed6e3 100%);
        padding: 1rem;
        border-radius: 10px;
        text-align: center;
        margin: 1rem 0;
    }

    /* Button styling */
    .stButton > button {
        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
        color: white;
        font-weight: bold;
        border: none;
        padding: 0.75rem 2rem;
        border-radius: 10px;
        transition: all 0.3s ease;
    }

    .stButton > button:hover {
        transform: translateY(-2px);
        box-shadow: 0 4px 12px rgba(0,0,0,0.15);
    }

    /* Success message */
    .success-box {
        background-color: #d4edda;
        color: #155724;
        padding: 1rem;
        border-radius: 10px;
        border-left: 4px solid #28a745;
        margin: 1rem 0;
    }

    /* Info box */
    .info-box {
        background-color: #d1ecf1;
        color: #0c5460;
        padding: 1rem;
        border-radius: 10px;
        border-left: 4px solid #17a2b8;
        margin: 1rem 0;
    }

    /* Number input styling */
    .stNumberInput input {
        font-size: 1.2rem;
        padding: 0.5rem;
    }

    /* Footer */
    .footer {
        text-align: center;
        padding: 2rem;
        margin-top: 2rem;
        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
        color: white;
        border-radius: 10px;
    }

    /* Animation */
    @keyframes fadeIn {
        from { opacity: 0; transform: translateY(20px); }
        to { opacity: 1; transform: translateY(0); }
    }

    .fade-in {
        animation: fadeIn 0.5s ease-out;
    }
</style>
""", unsafe_allow_html=True)

# Initialize session state
if 'calculation_history' not in st.session_state:
    st.session_state.calculation_history = []
if 'voucher_codes' not in st.session_state:
    st.session_state.voucher_codes = {
        "SAVE20": 20,
        "WELCOME10": 10,
        "FLASH25": 25,
        "VIP30": 30
    }

# Header
st.markdown("""
<div class="header-container">
    <h1>🎫 Voucher Discount Calculator</h1>
    <p style="font-size: 1.2rem;">Get amazing discounts with your voucher codes!</p>
</div>
""", unsafe_allow_html=True)

# Create two columns for main layout
col1, col2 = st.columns([1.5, 1])

with col1:
    st.markdown('<div class="card fade-in">', unsafe_allow_html=True)
    st.subheader("💰 Calculate Your Discount")

    # Input methods - Toggle between simple and voucher code
    input_method = st.radio(
        "Select input method:",
        ["Simple Voucher (Yes/No)", "Voucher Code System"],
        help="Choose how you want to apply your discount"
    )

    if input_method == "Simple Voucher (Yes/No)":
        # Simple yes/no voucher option
        has_voucher = st.radio(
            "Do you have a voucher?",
            ["No", "Yes"],
            horizontal=True,
            help="Select 'Yes' to get 20% discount"
        )

        # Price input with better formatting
        price = st.number_input(
            "Enter the price ($):",
            min_value=0.01,
            max_value=1000000.00,
            value=100.00,
            step=10.00,
            format="%.2f",
            help="Enter the original price of the item"
        )

        # Calculate discount
        if has_voucher == "Yes":
            discount = 0.2 * price
            discount_percent = 20
        else:
            discount = 0
            discount_percent = 0

        final_price = price - discount

        # Display results in a nice box
        col_a, col_b, col_c = st.columns(3)
        with col_a:
            st.metric("Original Price", f"${price:,.2f}")
        with col_b:
            st.metric("Discount", f"{discount_percent}%", delta=f"-${discount:,.2f}", delta_color="inverse")
        with col_c:
            st.metric("Final Price", f"${final_price:,.2f}", delta=f"Save ${discount:,.2f}")

    else:  # Voucher Code System
        # Advanced voucher code system
        st.markdown("### 🎟️ Enter Your Voucher Code")

        # Display available vouchers
        with st.expander("📋 Available Voucher Codes"):
            st.markdown("Here are some demo vouchers you can try:")
            for code, discount_percent in st.session_state.voucher_codes.items():
                st.code(f"{code} - {discount_percent}% OFF", language="text")

        # Voucher code input
        voucher_code = st.text_input(
            "Voucher Code:",
            placeholder="e.g., SAVE20, WELCOME10",
            help="Enter your voucher code here"
        ).upper().strip()

        # Price input
        price = st.number_input(
            "Enter the price ($):",
            min_value=0.01,
            max_value=1000000.00,
            value=100.00,
            step=10.00,
            format="%.2f"
        )

        # Validate and apply voucher
        if voucher_code:
            if voucher_code in st.session_state.voucher_codes:
                discount_percent = st.session_state.voucher_codes[voucher_code]
                discount = (discount_percent / 100) * price
                final_price = price - discount

                st.markdown(f"""
                <div class="success-box">
                    ✅ <strong>Voucher Applied Successfully!</strong><br>
                    You got {discount_percent}% OFF!
                </div>
                """, unsafe_allow_html=True)
            else:
                discount = 0
                final_price = price
                st.error(f"❌ Invalid voucher code: {voucher_code}")
                st.info("Try one of the available codes from the list above!")
        else:
            discount = 0
            final_price = price

        # Display results
        col_a, col_b, col_c = st.columns(3)
        with col_a:
            st.metric("Original Price", f"${price:,.2f}")
        with col_b:
            discount_show = discount if voucher_code and voucher_code in st.session_state.voucher_codes else 0
            percent_show = st.session_state.voucher_codes.get(voucher_code, 0) if voucher_code in st.session_state.voucher_codes else 0
            st.metric("Discount", f"{percent_show}%", delta=f"-${discount_show:,.2f}", delta_color="inverse")
        with col_c:
            st.metric("Final Price", f"${final_price:,.2f}")

    # Calculate button with animation
    st.markdown("---")

    if st.button("✨ Calculate Final Price", use_container_width=True):
        # Add to history
        calculation = {
            "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "original_price": price,
            "discount": discount,
            "final_price": final_price,
            "voucher_type": input_method
        }
        if input_method == "Simple Voucher (Yes/No)":
            calculation["has_voucher"] = has_voucher
        else:
            calculation["voucher_code"] = voucher_code if voucher_code else "None"

        st.session_state.calculation_history.append(calculation)

        # Success message with celebration
        st.balloons()
        st.markdown(f"""
        <div class="success-box fade-in">
            🎉 <strong>Calculation Complete!</strong><br>
            Original: ${price:,.2f} → Final: ${final_price:,.2f}<br>
            You saved: ${discount:,.2f}
        </div>
        """, unsafe_allow_html=True)

    st.markdown('</div>', unsafe_allow_html=True)

with col2:
    st.markdown('<div class="card fade-in">', unsafe_allow_html=True)
    st.subheader("📊 Quick Stats")

    # Show savings example
    st.markdown("### 💡 Did you know?")

    # Interactive savings calculator
    st.markdown("#### Calculate your savings:")
    example_price = st.slider("Select a price to see potential savings:", 10, 500, 100, 10)

    col_s1, col_s2 = st.columns(2)
    with col_s1:
        st.info(f"**Without Voucher**\n\n${example_price:.2f}")
    with col_s2:
        st.success(f"**With 20% Voucher**\n\n${example_price * 0.8:.2f}")
        st.caption(f"Save: ${example_price * 0.2:.2f}")

    st.markdown("---")

    # Recent calculations history
    st.markdown("### 📜 Recent Calculations")
    if st.session_state.calculation_history:
        recent = st.session_state.calculation_history[-5:]
        for calc in reversed(recent):
            st.markdown(f"""
            <div class="info-box" style="padding: 0.5rem; margin: 0.5rem 0;">
                <small>{calc['timestamp']}</small><br>
                <strong>${calc['original_price']:.2f}</strong> → <strong style="color: #28a745;">${calc['final_price']:.2f}</strong>
            </div>
            """, unsafe_allow_html=True)
    else:
        st.info("No calculations yet. Try calculating a price above!")

    st.markdown('</div>', unsafe_allow_html=True)

# File Upload Section (NEW!)
st.markdown("---")
st.markdown('<div class="card">', unsafe_allow_html=True)
st.subheader("📁 Upload and Manage Vouchers")

tab1, tab2, tab3 = st.tabs(["📤 Upload Voucher File", "📝 Bulk Vouchers", "💾 Export Data"])

with tab1:
    st.markdown("### Upload Voucher Codes File")

    uploaded_file = st.file_uploader(
        "Choose a file (CSV, JSON, or TXT)",
        type=['csv', 'json', 'txt'],
        help="Upload a file containing voucher codes and discounts"
    )

    if uploaded_file is not None:
        st.success(f"✅ File uploaded: {uploaded_file.name}")

        # Process different file types
        if uploaded_file.type == "text/csv" or uploaded_file.name.endswith('.csv'):
            df = pd.read_csv(uploaded_file)
            st.write("**Preview of uploaded file:**")
            st.dataframe(df, use_container_width=True)

            if 'code' in df.columns and 'discount' in df.columns:
                for _, row in df.iterrows():
                    st.session_state.voucher_codes[row['code'].upper()] = int(row['discount'])
                st.success(f"✅ Added {len(df)} voucher codes to the system!")
                st.json(st.session_state.voucher_codes)
            else:
                st.error("CSV must have 'code' and 'discount' columns")

        elif uploaded_file.type == "application/json" or uploaded_file.name.endswith('.json'):
            data = json.load(uploaded_file)
            if isinstance(data, dict):
                for code, discount in data.items():
                    st.session_state.voucher_codes[code.upper()] = discount
                st.success(f"✅ Added {len(data)} voucher codes from JSON!")
                st.json(st.session_state.voucher_codes)
            else:
                st.error("JSON should be a dictionary with code:discount pairs")

        elif uploaded_file.name.endswith('.txt'):
            content = uploaded_file.read().decode('utf-8')
            lines = content.split('\n')
            count = 0
            for line in lines:
                if ':' in line:
                    code, discount = line.split(':')
                    st.session_state.voucher_codes[code.upper().strip()] = int(discount.strip())
                    count += 1
            st.success(f"✅ Added {count} voucher codes from TXT file!")

with tab2:
    st.markdown("### Add Multiple Vouchers")
    st.markdown("Enter voucher codes in bulk (one per line in format: `CODE:DISCOUNT`)")

    bulk_vouchers = st.text_area(
        "Bulk voucher entries:",
        placeholder="SAVE20:20\nWELCOME10:10\nFLASH25:25\nBLACKFRIDAY:50",
        height=150
    )

    if st.button("Add Bulk Vouchers", use_container_width=True):
        lines = bulk_vouchers.strip().split('\n')
        added = 0
        for line in lines:
            if ':' in line:
                code, discount = line.split(':')
                st.session_state.voucher_codes[code.upper().strip()] = int(discount.strip())
                added += 1
        if added > 0:
            st.success(f"✅ Added {added} new voucher codes!")
            st.rerun()
        else:
            st.error("No valid voucher codes found. Use format: CODE:DISCOUNT")

with tab3:
    st.markdown("### Export Voucher Data")

    # Export current vouchers
    if st.button("📥 Export Vouchers as CSV", use_container_width=True):
        df_export = pd.DataFrame([
            {"Voucher Code": code, "Discount %": discount}
            for code, discount in st.session_state.voucher_codes.items()
        ])
        csv = df_export.to_csv(index=False)
        st.download_button(
            label="Download CSV",
            data=csv,
            file_name=f"vouchers_{datetime.now().strftime('%Y%m%d_%H%M%S')}.csv",
            mime="text/csv"
        )

    # Export calculation history
    if st.button("📥 Export Calculation History", use_container_width=True):
        if st.session_state.calculation_history:
            df_history = pd.DataFrame(st.session_state.calculation_history)
            csv_history = df_history.to_csv(index=False)
            st.download_button(
                label="Download History CSV",
                data=csv_history,
                file_name=f"calculations_{datetime.now().strftime('%Y%m%d_%H%M%S')}.csv",
                mime="text/csv"
            )
        else:
            st.warning("No calculation history to export")

st.markdown('</div>', unsafe_allow_html=True)

# Footer
st.markdown("""
<div class="footer">
    <p>🎫 Voucher Discount Calculator | Made with Streamlit</p>
    <p style="font-size: 0.8rem;">Upload CSV/JSON files to add custom voucher codes</p>
</div>
""", unsafe_allow_html=True)

# Sidebar with additional info
with st.sidebar:
    st.markdown("### 🎯 How to Use")
    st.markdown("""
    1. **Simple Voucher**: Just say Yes/No for 20% off
    2. **Voucher Code**: Enter codes like SAVE20
    3. **Upload File**: Add multiple vouchers at once
    4. **Export Data**: Download your calculations
    """)

    st.markdown("---")
    st.markdown("### 📊 Current Vouchers")
    for code, discount in st.session_state.voucher_codes.items():
        st.code(f"{code}: {discount}% OFF", language="text")

    st.markdown("---")
    st.markdown("### 💡 Pro Tips")
    st.markdown("""
    - Upload CSV with 'code' and 'discount' columns
    - JSON should be like: `{"SAVE20": 20, "WELCOME10": 10}`
    - TXT format: `CODE:DISCOUNT` per line
    """)

    if st.button("🔄 Reset to Default Vouchers"):
        st.session_state.voucher_codes = {
            "SAVE20": 20,
            "WELCOME10": 10,
            "FLASH25": 25,
            "VIP30": 30
        }
        st.success("Reset to default vouchers!")
        st.rerun()

pip install streamlit pandas numpy

!pip install streamlit